### ISSUE TITLE
Googly Eyes 1.12.0

### ISSUE THREAD

**Issue by ccar795** [iChun/GooglyEyes#18]
A little problem with player eyes that affects 7.0.1 and possibly 7.0.0 
1. Eye's never stay on the player heads face.
Link: https://imgur.com/a/spOR1

**Comment by iChun** [comment]
I need your mod list. I think this is a mod conflict.

**Comment by ccar795** [comment]
Currently installed mods: https://gyazo.com/1acf14654e7de61fd58642511825ba94
I think the culprit is most likely more player models.

**Comment by MakerTim** [comment]
Got the same issue
Tracked it down = happens when i got placementpreview (placementpreview-1.12.0-0.3.1) installed

(mod list) https://puu.sh/xQ10x.png

https://puu.sh/xQ0tn.png - issue is there with placementpreview
witout its working fine :)

Log
https://pastebin.com/raw/QYwgUZX1


hope you can find the problem with it <3

EDIT: fixed link of modlist

**Comment by iChun** [comment]
I can't seem to replicate it with either of those mods installed.

**Comment by iChun** [comment]
I'm gonna try something, a config in iChunUtil, when 7.0.2 is released.
Please try that out and let me know how it goes. It'll be called aggressive
head tracking and it's turned off by default.

**Comment by ccar795** [comment]
Will do.

**Comment by ccar795** [comment]
Okay, so I tried the recent release 7.0.2 for googly eyes and ichunutil and the aggressive head tracking works. What I can also confirm is that "more player models" is causing the eyes not to stick to the face.

**Comment by iChun** [comment]
Glad it's fixed, I couldn't really replicate it, probably some steps I'm
missing though. I'll try to optimise it for just the player as a config in
the future and maybe add the legacy methods back in later on as well.
